import type { Question } from '@/content/schemas';

/**
 * Objective 3.4 — Explain the importance of resilience and recovery in security architecture.
 *
 * Every question is original, written from the published objective. None reproduces,
 * paraphrases, or reconstructs any real exam item — see NOTICE.md.
 */
const choice = (
  id: 'a' | 'b' | 'c' | 'd',
  en: string,
  fr: string,
  correct: boolean,
  enExplanation: string,
  frExplanation: string,
) => ({
  id,
  text: { en, fr },
  correct,
  explanation: { en: enExplanation, fr: frExplanation },
});

export const QUESTIONS_3_4: Question[] = [
  {
    id: 'q-3-4-001',
    objective: '3.4',
    kind: 'recall',
    difficulty: 'easy',
    prompt: {
      en: 'What is the primary purpose of high availability?',
      fr: 'Quelle est la finalité principale de la haute disponibilité ?',
    },
    options: [
      choice(
        'a',
        'Keep a service available when an individual component fails',
        'Maintenir un service disponible lorsqu’un composant individuel tombe en panne',
        true,
        'High availability uses redundancy and failover to reduce interruption after a component failure. It is concerned with continued service, not merely keeping a spare copy of data.',
        'La haute disponibilité utilise redondance et basculement pour réduire l’interruption après une panne de composant. Elle vise la continuité du service, pas une simple copie de données.',
      ),
      choice(
        'b',
        'Preserve a historical copy of data for later restoration',
        'Conserver une copie historique des données pour une restauration ultérieure',
        false,
        'Preserving an earlier recoverable copy is the role of a backup. A backup is important to recovery but normally cannot answer live requests after a server failure.',
        'Conserver une copie récupérable antérieure relève de la sauvegarde. Elle est importante pour la reprise, mais ne répond normalement pas aux requêtes en direct après une panne de serveur.',
      ),
      choice(
        'c',
        'Prevent all maintenance outages from occurring',
        'Empêcher toute interruption liée à la maintenance',
        false,
        'High availability reduces unplanned interruption through design choices, but planned work can still require coordination or controlled downtime. It does not make every maintenance activity disappear.',
        'La haute disponibilité réduit les interruptions imprévues par la conception, mais un travail planifié peut encore demander coordination ou arrêt contrôlé. Elle ne supprime pas toute maintenance.',
      ),
      choice(
        'd',
        'Prove that recovered data has not changed',
        'Prouver que des données restaurées ne sont pas modifiées',
        false,
        'Integrity verification can be part of recovery testing, but it is not the defining purpose of high availability. HA addresses service continuity during a failure.',
        'La vérification de l’intégrité peut faire partie d’un test de reprise, mais elle ne définit pas la haute disponibilité. La HA traite la continuité du service pendant une panne.',
      ),
    ],
  },
  {
    id: 'q-3-4-002',
    objective: '3.4',
    kind: 'scenario',
    difficulty: 'medium',
    prompt: {
      en: 'An application has two web servers, but both depend on the same power distribution unit. Which risk remains?',
      fr: 'Une application possède deux serveurs web, mais les deux dépendent de la même unité de distribution électrique. Quel risque subsiste ?',
    },
    options: [
      choice(
        'a',
        'A shared power failure can disable both servers',
        'Une panne électrique partagée peut désactiver les deux serveurs',
        true,
        'The servers are redundant only above the shared power dependency. Failure of that distribution unit is a common mode that can remove both supposedly separate instances.',
        'Les serveurs ne sont redondants qu’au-dessus de la dépendance électrique partagée. La panne de cette unité constitue un mode commun pouvant retirer les deux instances.',
      ),
      choice(
        'b',
        'A missing backup prevents the load balancer from distributing traffic',
        'Une sauvegarde absente empêche le répartiteur de charge de distribuer le trafic',
        false,
        'A backup preserves data for restoration and does not supply power or health information to a load balancer. The stated weakness is the shared electrical dependency.',
        'Une sauvegarde conserve des données pour restauration et ne fournit ni alimentation ni état de santé au répartiteur. La faiblesse indiquée est la dépendance électrique commune.',
      ),
      choice(
        'c',
        'Platform diversity prevents a local power outage',
        'La diversité de plateformes empêche une coupure électrique locale',
        false,
        'Different platforms can reduce a technology-specific common failure, but they do not alter a common electrical path. Physical dependencies need physical resilience measures.',
        'Des plateformes différentes peuvent réduire une panne technologique commune, mais ne modifient pas un chemin électrique commun. Les dépendances physiques exigent des mesures physiques.',
      ),
      choice(
        'd',
        'A warm site automatically supplies redundant electricity',
        'Un site tiède fournit automatiquement une alimentation redondante',
        false,
        'A warm site describes alternate-site readiness, not the power design inside the current facility. It may help after site loss but does not remove this local single point.',
        'Un site tiède décrit la préparation d’un site alternatif, non la conception électrique du bâtiment actuel. Il peut aider après perte du site sans supprimer ce point unique local.',
      ),
    ],
  },
  {
    id: 'q-3-4-003',
    objective: '3.4',
    kind: 'discrimination',
    difficulty: 'medium',
    prompt: {
      en: 'Which statement best distinguishes a hot site from a cold site?',
      fr: 'Quelle affirmation distingue le mieux un site chaud d’un site froid ?',
    },
    options: [
      choice(
        'a',
        'A hot site is prepared for rapid operation; a cold site requires substantial setup',
        'Un site chaud est préparé pour fonctionner rapidement ; un site froid exige une mise en place importante',
        true,
        'The readiness of facilities, systems, and data is the central distinction. Greater readiness shortens recovery time but normally costs more to maintain.',
        'Le niveau de préparation des installations, systèmes et données est la distinction centrale. Une plus grande préparation réduit le délai de reprise, mais coûte généralement davantage.',
      ),
      choice(
        'b',
        'A hot site stores backups; a cold site stores only replicas',
        'Un site chaud stocke des sauvegardes ; un site froid ne stocke que des répliques',
        false,
        'Backup and replication strategies are separate from the hot, warm, and cold site categories. Any site strategy can require protected data copies appropriate to recovery needs.',
        'Les stratégies de sauvegarde et réplication sont distinctes des catégories chaud, tiède et froid. Toute stratégie de site peut exiger des copies protégées adaptées aux besoins.',
      ),
      choice(
        'c',
        'A hot site uses two cloud providers; a cold site uses one provider',
        'Un site chaud utilise deux fournisseurs de nuage ; un site froid utilise un seul fournisseur',
        false,
        'Provider count describes multi-cloud design, whereas hot and cold describe operational readiness of an alternate location. These concepts can be combined but are not definitions.',
        'Le nombre de fournisseurs décrit une conception multi-cloud, tandis que chaud et froid décrivent la préparation opérationnelle d’un lieu alternatif. Les concepts peuvent se combiner sans se définir.',
      ),
      choice(
        'd',
        'A hot site eliminates the need to test recovery procedures',
        'Un site chaud supprime le besoin de tester les procédures de reprise',
        false,
        'Prepared equipment does not prove that failover, access, data, and procedures will work together. Testing remains necessary for every alternate-site strategy.',
        'Des équipements préparés ne prouvent pas que basculement, accès, données et procédures fonctionneront ensemble. Les tests restent nécessaires pour toute stratégie de site alternatif.',
      ),
    ],
  },
  {
    id: 'q-3-4-004',
    objective: '3.4',
    kind: 'scenario',
    difficulty: 'hard',
    prompt: {
      en: 'A regional flood makes the primary office inaccessible. The business needs a prearranged location with some infrastructure, but can tolerate time to install its applications and current data. Which site fits best?',
      fr: 'Une inondation régionale rend le bureau principal inaccessible. L’entreprise a besoin d’un lieu prévu avec une partie de l’infrastructure, mais peut accepter le temps d’installer applications et données récentes. Quel site convient le mieux ?',
    },
    options: [
      choice(
        'a',
        'Warm site',
        'Site tiède',
        true,
        'A warm site has partial infrastructure ready while systems or data still need completion. That matches the stated balance between preparation and tolerated recovery time.',
        'Un site tiède possède une infrastructure partiellement prête tandis que systèmes ou données restent à compléter. Cela correspond au compromis indiqué entre préparation et délai acceptable.',
      ),
      choice(
        'b',
        'Hot site',
        'Site chaud',
        false,
        'A hot site is chosen when operations must resume very quickly with a highly prepared environment. The scenario explicitly permits setup time, so that costlier readiness is unnecessary.',
        'Un site chaud convient lorsque les opérations doivent reprendre très vite dans un environnement très préparé. Le scénario autorise une mise en place, donc cette disponibilité coûteuse est excessive.',
      ),
      choice(
        'c',
        'Cold site',
        'Site froid',
        false,
        'A cold site supplies little ready computing capability and therefore requires the most setup. The scenario requires some infrastructure to have been prepared already.',
        'Un site froid fournit peu de capacité informatique prête et demande donc le plus de préparation. Le scénario exige qu’une partie de l’infrastructure soit déjà disponible.',
      ),
      choice(
        'd',
        'Active-active cluster',
        'Cluster actif-actif',
        false,
        'A cluster can provide component-level availability, but it is not an alternate-site category. The disruption removes access to a location, which calls for site recovery planning.',
        'Un cluster peut fournir de la disponibilité au niveau des composants, mais ce n’est pas une catégorie de site alternatif. La perturbation retire l’accès à un lieu, donc appelle une stratégie de site.',
      ),
    ],
  },
  {
    id: 'q-3-4-005',
    objective: '3.4',
    kind: 'recall',
    difficulty: 'easy',
    prompt: {
      en: 'What is the resilience benefit of platform diversity?',
      fr: 'Quel est le bénéfice de résilience de la diversité de plateformes ?',
    },
    options: [
      choice(
        'a',
        'It can reduce exposure to one platform-specific common failure',
        'Elle peut réduire l’exposition à une panne commune propre à une plateforme',
        true,
        'Using different platforms can prevent one implementation flaw or vendor-specific outage from affecting every service. It only helps when the diversity removes a real shared dependency.',
        'L’emploi de plateformes différentes peut empêcher qu’un défaut de mise en œuvre ou une panne propre à un fournisseur touche chaque service. Cela aide seulement si une dépendance commune disparaît.',
      ),
      choice(
        'b',
        'It guarantees that all systems use identical security settings',
        'Elle garantit que tous les systèmes utilisent des paramètres de sécurité identiques',
        false,
        'Identical settings are easier with a standard platform, not with diverse ones. Diversity often increases configuration and hardening effort rather than eliminating it.',
        'Des paramètres identiques sont plus faciles avec une plateforme standard, non avec des plateformes diverses. La diversité augmente souvent l’effort de configuration et de durcissement.',
      ),
      choice(
        'c',
        'It replaces the need for capacity planning during failures',
        'Elle remplace le besoin de planification de capacité pendant les pannes',
        false,
        'Different platforms do not create compute, bandwidth, storage, or licences. Surviving systems still need enough capacity to handle the failed system’s workload.',
        'Des plateformes différentes ne créent ni calcul, ni bande passante, ni stockage, ni licences. Les systèmes survivants doivent toujours pouvoir absorber la charge du système défaillant.',
      ),
      choice(
        'd',
        'It ensures that data can be restored from a backup',
        'Elle garantit que les données peuvent être restaurées depuis une sauvegarde',
        false,
        'Restore success depends on backup scope, protection, procedures, and testing. Platform diversity may complicate restoration and does not itself create a recoverable data copy.',
        'Le succès de restauration dépend du périmètre, de la protection, des procédures et des tests. La diversité peut compliquer la restauration et ne crée pas elle-même une copie récupérable.',
      ),
    ],
  },
  {
    id: 'q-3-4-006',
    objective: '3.4',
    kind: 'discrimination',
    difficulty: 'medium',
    prompt: {
      en: 'Which requirement most directly calls for a multi-cloud system?',
      fr: 'Quelle exigence appelle le plus directement un système multi-cloud ?',
    },
    options: [
      choice(
        'a',
        'Reduce dependence on a single cloud provider’s availability',
        'Réduire la dépendance à la disponibilité d’un seul fournisseur de nuage',
        true,
        'Multi-cloud uses more than one cloud provider, so it can reduce provider-specific dependency. The application and its data still need a design that can use both environments.',
        'Le multi-cloud utilise plusieurs fournisseurs de nuage et peut donc réduire la dépendance propre à un fournisseur. L’application et ses données doivent encore pouvoir utiliser les deux environnements.',
      ),
      choice(
        'b',
        'Bridge a short electrical interruption at one rack',
        'Franchir une brève interruption électrique dans un rack',
        false,
        'A UPS is designed to bridge a short power event or enable shutdown. Additional cloud providers do not protect equipment already losing local electrical power.',
        'Un UPS est conçu pour franchir une brève coupure ou permettre un arrêt. Des fournisseurs de nuage supplémentaires ne protègent pas un équipement qui perd déjà son alimentation locale.',
      ),
      choice(
        'c',
        'Restore a file that was deleted last week',
        'Restaurer un fichier supprimé la semaine précédente',
        false,
        'Recovery of an earlier file version depends on backups with suitable retention and tested restore procedures. Multi-cloud can duplicate a current deletion rather than preserve history.',
        'La récupération d’une ancienne version dépend de sauvegardes avec conservation adaptée et de restaurations testées. Le multi-cloud peut dupliquer une suppression actuelle au lieu de préserver l’historique.',
      ),
      choice(
        'd',
        'Keep two application servers sharing one local network',
        'Garder deux serveurs applicatifs partageant un même réseau local',
        false,
        'Two local servers are a high-availability design choice, not evidence of multiple cloud providers. They may improve host resilience while retaining local shared dependencies.',
        'Deux serveurs locaux relèvent de la haute disponibilité, non de plusieurs fournisseurs de nuage. Ils peuvent améliorer la résilience des hôtes tout en conservant des dépendances locales.',
      ),
    ],
  },
  {
    id: 'q-3-4-007',
    objective: '3.4',
    kind: 'scenario',
    difficulty: 'medium',
    prompt: {
      en: 'A company restores all technical systems after an outage, but its call-center staff cannot authenticate remotely and do not know the temporary customer process. What was incomplete?',
      fr: 'Une entreprise rétablit tous ses systèmes techniques après une panne, mais le personnel du centre d’appels ne peut pas s’authentifier à distance et ignore le processus client temporaire. Qu’est-ce qui était incomplet ?',
    },
    options: [
      choice(
        'a',
        'Continuity of operations planning',
        'La planification de continuité des opérations',
        true,
        'Continuity includes people, procedures, communications, and alternate work arrangements as well as systems. Restoring technology alone does not sustain an essential business function.',
        'La continuité comprend personnes, procédures, communications et modes de travail alternatifs en plus des systèmes. Restaurer seulement la technique ne maintient pas une fonction métier essentielle.',
      ),
      choice(
        'b',
        'Load balancing configuration',
        'La configuration de la répartition de charge',
        false,
        'Load balancing directs technical requests among healthy instances. It cannot provide remote identity access or teach staff an alternate business procedure.',
        'La répartition de charge dirige des requêtes techniques entre instances saines. Elle ne peut ni fournir un accès d’identité distant ni enseigner une procédure métier alternative.',
      ),
      choice(
        'c',
        'Platform diversity',
        'La diversité de plateformes',
        false,
        'Different technology platforms may reduce a shared technical weakness, but the scenario describes unprepared people and processes. That is a continuity planning failure.',
        'Des plateformes différentes peuvent réduire une faiblesse technique commune, mais le scénario décrit des personnes et processus non préparés. C’est une défaillance de planification de continuité.',
      ),
      choice(
        'd',
        'A generator maintenance schedule',
        'Un calendrier de maintenance du générateur',
        false,
        'The systems are already restored, and the failure concerns remote access and instructions. Generator maintenance is relevant to power resilience, not the stated operational gap.',
        'Les systèmes sont déjà rétablis et la défaillance concerne accès distant et consignes. La maintenance du générateur relève de la résilience électrique, non de l’écart opérationnel indiqué.',
      ),
    ],
  },
  {
    id: 'q-3-4-008',
    objective: '3.4',
    kind: 'discrimination',
    difficulty: 'hard',
    prompt: {
      en: 'After one database node fails, the remaining node reaches 95% utilisation and response times become unacceptable. Which planning activity should have identified this risk?',
      fr: 'Après la panne d’un nœud de base de données, le nœud restant atteint 95 % d’utilisation et les temps de réponse deviennent inacceptables. Quelle activité devait identifier ce risque ?',
    },
    options: [
      choice(
        'a',
        'Capacity planning',
        'La planification de capacité',
        true,
        'Capacity planning evaluates whether surviving resources can carry expected load during demand changes and failures. A redundant design without sufficient headroom still loses acceptable service.',
        'La planification de capacité évalue si les ressources survivantes peuvent supporter la charge lors de changements de demande et pannes. Une conception redondante sans marge perd encore un service acceptable.',
      ),
      choice(
        'b',
        'Backup retention planning',
        'La planification de conservation des sauvegardes',
        false,
        'Retention determines how long recoverable copies are kept, not whether a live database node has enough processing capacity. This is an availability performance problem.',
        'La conservation détermine combien de temps les copies récupérables sont gardées, non si un nœud actif possède assez de capacité de traitement. C’est un problème de disponibilité et performance.',
      ),
      choice(
        'c',
        'Geographic separation planning',
        'La planification de séparation géographique',
        false,
        'Geographic separation reduces the chance that one regional event removes both sites. It does not calculate the load remaining local nodes must carry after a node failure.',
        'La séparation géographique réduit le risque qu’un événement régional retire les deux sites. Elle ne calcule pas la charge que les nœuds locaux restants doivent absorber après une panne.',
      ),
      choice(
        'd',
        'A tabletop communication exercise',
        'Un exercice sur table de communication',
        false,
        'A tabletop exercise can test decisions and notification, but it does not demonstrate compute headroom under a real workload. Capacity needs measurement and failure testing.',
        'Un exercice sur table peut tester décisions et notifications, mais ne démontre pas la marge de calcul sous charge réelle. La capacité exige mesures et tests de panne.',
      ),
    ],
  },
  {
    id: 'q-3-4-009',
    objective: '3.4',
    kind: 'recall',
    difficulty: 'easy',
    prompt: {
      en: 'Why is recovery testing important even when backup jobs report success?',
      fr: 'Pourquoi les tests de reprise sont-ils importants même lorsque les tâches de sauvegarde signalent un succès ?',
    },
    options: [
      choice(
        'a',
        'They prove that data and procedures can actually be restored and used',
        'Ils prouvent que données et procédures peuvent réellement être restaurées et utilisées',
        true,
        'A successful copy operation does not demonstrate usable data, correct permissions, compatible systems, or an achievable recovery time. A restore test evaluates the outcome that matters.',
        'Une copie réussie ne démontre ni données utilisables, ni droits corrects, ni systèmes compatibles, ni délai de reprise atteignable. Un test de restauration évalue le résultat important.',
      ),
      choice(
        'b',
        'They make replication unnecessary for available services',
        'Ils rendent la réplication inutile pour les services disponibles',
        false,
        'Testing validates a recovery capability; it does not provide a live secondary copy for availability. Replication and backups address different resilience needs and may both be required.',
        'Les tests valident une capacité de reprise ; ils ne fournissent pas une copie secondaire active pour la disponibilité. Réplication et sauvegardes traitent des besoins différents et peuvent coexister.',
      ),
      choice(
        'c',
        'They guarantee that a future incident cannot occur',
        'Ils garantissent qu’un incident futur ne peut pas survenir',
        false,
        'Testing reduces uncertainty about a plan, not the possibility of disruption itself. New failures, changes, and dependencies can still create incidents after a successful test.',
        'Les tests réduisent l’incertitude sur un plan, non la possibilité d’une perturbation. De nouvelles pannes, changements et dépendances peuvent encore créer des incidents après un test réussi.',
      ),
      choice(
        'd',
        'They replace the need to protect backup copies',
        'Ils remplacent le besoin de protéger les copies de sauvegarde',
        false,
        'Tests do not provide confidentiality or integrity for stored backup media. Backup copies remain valuable targets and need access, storage, and handling protections.',
        'Les tests ne fournissent ni confidentialité ni intégrité aux supports de sauvegarde. Les copies restent des cibles précieuses et exigent protections d’accès, stockage et manipulation.',
      ),
    ],
  },
  {
    id: 'q-3-4-010',
    objective: '3.4',
    kind: 'scenario',
    difficulty: 'hard',
    prompt: {
      en: 'A ransomware event encrypts a production file share. The organisation has a continuously replicated secondary share, but it also contains the encrypted files. What should the recovery team use first?',
      fr: 'Un rançongiciel chiffre un partage de fichiers de production. L’organisation possède un partage secondaire répliqué en continu, mais il contient aussi les fichiers chiffrés. Que doit utiliser l’équipe de reprise en premier ?',
    },
    options: [
      choice(
        'a',
        'A retained backup from before the encryption event',
        'Une sauvegarde conservée avant l’événement de chiffrement',
        true,
        'Continuous replication can propagate corruption or malicious encryption immediately. A retained backup offers an earlier recovery point that may contain unencrypted, usable files.',
        'La réplication continue peut propager immédiatement corruption ou chiffrement malveillant. Une sauvegarde conservée offre un point de reprise antérieur avec des fichiers utilisables non chiffrés.',
      ),
      choice(
        'b',
        'The current replica, because replication is always a backup',
        'La réplique actuelle, car la réplication est toujours une sauvegarde',
        false,
        'A replica is often designed for current availability, not historical recovery. Here it has copied the damage, so it cannot supply the required clean point in time.',
        'Une réplique vise souvent la disponibilité actuelle, non la reprise historique. Ici, elle a copié le dommage et ne peut donc fournir le point dans le temps sain demandé.',
      ),
      choice(
        'c',
        'A load balancer, because it can redirect users away from the files',
        'Un répartiteur de charge, car il peut rediriger les utilisateurs loin des fichiers',
        false,
        'A load balancer can distribute requests among service instances but cannot decrypt or restore damaged data. The problem is data recovery, not request distribution.',
        'Un répartiteur de charge peut distribuer les requêtes entre instances, mais ne peut ni déchiffrer ni restaurer des données endommagées. Le problème est la reprise de données, non le trafic.',
      ),
      choice(
        'd',
        'A UPS, because it protects file integrity during outages',
        'Un UPS, car il protège l’intégrité des fichiers pendant les coupures',
        false,
        'A UPS can bridge electrical loss and support orderly shutdown, but it does not reverse ransomware encryption. The event requires a recoverable historical data copy.',
        'Un UPS peut franchir une perte électrique et soutenir un arrêt ordonné, mais ne renverse pas le chiffrement par rançongiciel. L’événement exige une copie historique récupérable.',
      ),
    ],
  },
  {
    id: 'q-3-4-011',
    objective: '3.4',
    kind: 'recall',
    difficulty: 'easy',
    prompt: {
      en: 'What is a UPS primarily intended to provide?',
      fr: 'Que vise principalement à fournir un UPS ?',
    },
    options: [
      choice(
        'a',
        'Short-term power during an interruption or time for orderly shutdown',
        'Une alimentation de courte durée pendant une interruption ou le temps d’un arrêt ordonné',
        true,
        'A UPS bridges a short power event so equipment can continue briefly, fail over, or shut down safely. It is not normally the long-duration source for an extended outage.',
        'Un UPS franchit une brève coupure afin que les équipements continuent, basculent ou s’arrêtent proprement. Ce n’est normalement pas la source de longue durée d’une panne prolongée.',
      ),
      choice(
        'b',
        'Long-term generation of electricity without fuel',
        'La production d’électricité à long terme sans carburant',
        false,
        'Longer duration can be provided by a generator, which itself needs fuel and maintenance. A UPS has limited stored energy and is intended for a shorter interval.',
        'Une durée plus longue peut être fournie par un générateur, qui exige lui-même carburant et maintenance. Un UPS possède une énergie stockée limitée et vise un intervalle plus court.',
      ),
      choice(
        'c',
        'A separate historical copy of application data',
        'Une copie historique distincte des données applicatives',
        false,
        'A backup system keeps recoverable data copies. A UPS supplies electrical continuity and may prevent abrupt shutdown, but it does not retain a separate data history.',
        'Un système de sauvegarde conserve des copies récupérables. Un UPS fournit une continuité électrique et peut éviter un arrêt brutal, mais ne conserve pas un historique distinct.',
      ),
      choice(
        'd',
        'Automatic distribution of traffic between application servers',
        'La distribution automatique du trafic entre serveurs applicatifs',
        false,
        'Traffic distribution is the role of a load balancer or similar availability component. A UPS provides power to equipment and does not inspect or route application requests.',
        'La distribution du trafic relève d’un répartiteur de charge ou composant similaire. Un UPS alimente les équipements et n’inspecte ni ne route les requêtes applicatives.',
      ),
    ],
  },
  {
    id: 'q-3-4-012',
    objective: '3.4',
    kind: 'discrimination',
    difficulty: 'medium',
    prompt: {
      en: 'Which control pair most directly addresses a utility outage that may last several hours? (Select all that apply.)',
      fr: 'Quelle paire de contrôles traite le plus directement une coupure du réseau électrique pouvant durer plusieurs heures ? (Sélectionnez toutes les réponses correctes.)',
    },
    multiSelect: true,
    options: [
      choice(
        'a',
        'UPS for the immediate transition',
        'UPS pour la transition immédiate',
        true,
        'A UPS bridges the initial power loss and can keep systems stable while another source starts. It also supports an orderly shutdown if the longer source is unavailable.',
        'Un UPS franchit la perte initiale d’alimentation et maintient les systèmes stables pendant le démarrage d’une autre source. Il soutient aussi un arrêt ordonné si cette source manque.',
      ),
      choice(
        'b',
        'Generator with maintained fuel supply',
        'Générateur avec approvisionnement en carburant entretenu',
        true,
        'A generator can provide longer-running power, provided fuel and maintenance support it. That duration addresses the stated multi-hour outage beyond a UPS battery interval.',
        'Un générateur peut fournir une alimentation plus durable si carburant et maintenance le permettent. Cette durée traite la coupure de plusieurs heures au-delà de la batterie d’un UPS.',
      ),
      choice(
        'c',
        'A current data replica in another storage system',
        'Une réplique actuelle des données dans un autre stockage',
        false,
        'A replica can support data availability or recovery but does not energise local systems. The scenario asks specifically about sustaining electrical power during a utility outage.',
        'Une réplique peut soutenir disponibilité ou reprise de données, mais n’alimente pas les systèmes locaux. Le scénario demande précisément comment maintenir l’électricité pendant une coupure.',
      ),
      choice(
        'd',
        'A hot site classification without a power design',
        'Une classification de site chaud sans conception électrique',
        false,
        'A hot site may be useful for major site loss, but the label alone does not provide power. Its own electrical dependencies still require UPS, generation, or redundant feeds.',
        'Un site chaud peut aider lors d’une perte majeure de site, mais son étiquette ne fournit pas d’électricité. Ses dépendances exigent aussi UPS, génération ou arrivées redondantes.',
      ),
    ],
  },
  {
    id: 'q-3-4-013',
    objective: '3.4',
    kind: 'scenario',
    difficulty: 'medium',
    prompt: {
      en: 'A company runs its workload in two regions of one cloud provider. Which resilience statement is most accurate?',
      fr: 'Une entreprise exécute sa charge dans deux régions d’un même fournisseur de nuage. Quelle affirmation de résilience est la plus exacte ?',
    },
    options: [
      choice(
        'a',
        'It can reduce exposure to a regional outage but still depends on one provider',
        'Elle peut réduire l’exposition à une panne régionale tout en dépendant encore d’un seul fournisseur',
        true,
        'Two regions can provide geographic resilience against a regional failure. Because both use one provider, a provider-wide dependency remains and this is not multi-cloud.',
        'Deux régions peuvent fournir une résilience géographique contre une panne régionale. Comme les deux utilisent un fournisseur, une dépendance globale subsiste et ce n’est pas du multi-cloud.',
      ),
      choice(
        'b',
        'It is multi-cloud because two geographic locations are used',
        'C’est du multi-cloud car deux emplacements géographiques sont utilisés',
        false,
        'Multi-cloud means more than one cloud provider, not more than one region. Geographic redundancy and provider diversity are related but distinct architectural decisions.',
        'Le multi-cloud signifie plusieurs fournisseurs de nuage, non plusieurs régions. Redondance géographique et diversité de fournisseurs sont des décisions liées mais distinctes.',
      ),
      choice(
        'c',
        'It removes the need for backup retention',
        'Elle supprime le besoin de conservation des sauvegardes',
        false,
        'Regional copies can replicate accidental deletion or corruption just as quickly as valid data. Backups with retention provide historical recovery points that current regional replicas may lack.',
        'Les copies régionales peuvent répliquer suppression ou corruption aussi vite que les données valides. Des sauvegardes conservées fournissent des points historiques qu’une réplique actuelle peut ne pas offrir.',
      ),
      choice(
        'd',
        'It guarantees capacity after a regional failover',
        'Elle garantit la capacité après un basculement régional',
        false,
        'A second region needs sufficient tested capacity to handle the workload after failover. Merely existing in another region does not prove it has required compute, bandwidth, or licences.',
        'Une seconde région doit posséder une capacité testée suffisante après basculement. Sa simple existence ne prouve ni calcul, ni bande passante, ni licences nécessaires.',
      ),
    ],
  },
  {
    id: 'q-3-4-014',
    objective: '3.4',
    kind: 'discrimination',
    difficulty: 'hard',
    prompt: {
      en: 'Which two activities provide the strongest evidence that a recovery plan can meet its intended outcome? (Select all that apply.)',
      fr: 'Quelles deux activités fournissent la preuve la plus forte qu’un plan de reprise peut atteindre son résultat attendu ? (Sélectionnez toutes les réponses correctes.)',
    },
    multiSelect: true,
    options: [
      choice(
        'a',
        'Perform a technical restore and verify that the application can use the data',
        'Effectuer une restauration technique et vérifier que l’application utilise les données',
        true,
        'A technical restore validates the practical result: accessible data, functioning systems, and usable application behaviour. It directly tests more than the existence of written procedures.',
        'Une restauration technique valide le résultat pratique : données accessibles, systèmes fonctionnels et comportement applicatif utilisable. Elle teste directement davantage que l’existence de procédures écrites.',
      ),
      choice(
        'b',
        'Run a failover exercise under conditions that represent the service load',
        'Exécuter un exercice de basculement dans des conditions représentatives de la charge',
        true,
        'A representative failover exercise tests routing, dependencies, and whether surviving capacity is adequate. It produces evidence that the designed transition works under relevant conditions.',
        'Un exercice de basculement représentatif teste routage, dépendances et capacité survivante. Il produit une preuve que la transition conçue fonctionne dans des conditions pertinentes.',
      ),
      choice(
        'c',
        'Declare the plan complete after stakeholders approve the document',
        'Déclarer le plan terminé après approbation du document par les parties prenantes',
        false,
        'Approval establishes ownership and agreement, but it cannot demonstrate that systems, contacts, credentials, and procedures work during a real recovery. Testing supplies that evidence.',
        'L’approbation établit responsabilité et accord, mais ne démontre pas que systèmes, contacts, identifiants et procédures fonctionnent pendant une reprise. Les tests fournissent cette preuve.',
      ),
      choice(
        'd',
        'Keep a single current replica without ever restoring it',
        'Conserver une unique réplique actuelle sans jamais la restaurer',
        false,
        'A current replica may improve availability but does not prove recoverability or historical protection. Without testing, it may be inaccessible, incomplete, or contain copied corruption.',
        'Une réplique actuelle peut améliorer disponibilité, mais ne prouve ni récupérabilité ni protection historique. Sans test, elle peut être inaccessible, incomplète ou contenir une corruption copiée.',
      ),
    ],
  },
  {
    id: 'q-3-4-015',
    objective: '3.4',
    kind: 'scenario',
    difficulty: 'hard',
    prompt: {
      en: 'An organisation wants its payment service to remain available after one host failure, recover a clean version after data corruption, and operate during a brief utility interruption. Which design is best?',
      fr: 'Une organisation veut que son service de paiement reste disponible après la panne d’un hôte, récupère une version saine après corruption de données et fonctionne durant une brève coupure électrique. Quelle conception convient le mieux ?',
    },
    options: [
      choice(
        'a',
        'Redundant hosts with failover, retained backups, and a UPS',
        'Des hôtes redondants avec basculement, des sauvegardes conservées et un UPS',
        true,
        'Failover addresses host availability, retained backups provide an earlier clean recovery point, and a UPS bridges short power loss. Each control directly addresses one stated requirement.',
        'Le basculement traite disponibilité des hôtes, les sauvegardes conservées fournissent un point de reprise sain antérieur, et un UPS franchit une brève perte électrique. Chaque contrôle traite un besoin.',
      ),
      choice(
        'b',
        'One powerful host, continuous replication, and a generator only',
        'Un hôte puissant, une réplication continue et seulement un générateur',
        false,
        'A single host remains a single point of failure, and replication can copy corruption. A generator may help power duration but does not solve the missing host or historical recovery controls.',
        'Un hôte unique reste un point unique de panne, et la réplication peut copier une corruption. Un générateur peut aider pour la durée électrique sans résoudre l’hôte ni la reprise historique.',
      ),
      choice(
        'c',
        'Platform diversity, a cold site, and encrypted backups',
        'Diversité de plateformes, site froid et sauvegardes chiffrées',
        false,
        'These controls can be useful, but a cold site is not the direct answer to brief host failure or short power loss. The design also omits explicit live failover capability.',
        'Ces contrôles peuvent être utiles, mais un site froid ne répond pas directement à une brève panne d’hôte ou électrique. La conception omet aussi une capacité explicite de basculement en direct.',
      ),
      choice(
        'd',
        'A multi-cloud contract and a documented recovery plan',
        'Un contrat multi-cloud et un plan de reprise documenté',
        false,
        'Provider diversity and documentation alone do not create failover, retained recovery points, or short-term local power. The stated outcomes require implemented and tested technical controls.',
        'Diversité de fournisseurs et documentation seules ne créent ni basculement, ni points de reprise conservés, ni alimentation locale brève. Les résultats demandés exigent des contrôles techniques appliqués et testés.',
      ),
    ],
  },
];
